// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	model "github.com/maxwelbm/alkemy-g7.git/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockIInboundOrderService is an autogenerated mock type for the IInboundOrderService type
type MockIInboundOrderService struct {
	mock.Mock
}

// Post provides a mock function with given fields: inboundOrder
func (_m *MockIInboundOrderService) Post(inboundOrder model.InboundOrder) (model.InboundOrder, error) {
	ret := _m.Called(inboundOrder)

	if len(ret) == 0 {
		panic("no return value specified for Post")
	}

	var r0 model.InboundOrder
	var r1 error
	if rf, ok := ret.Get(0).(func(model.InboundOrder) (model.InboundOrder, error)); ok {
		return rf(inboundOrder)
	}
	if rf, ok := ret.Get(0).(func(model.InboundOrder) model.InboundOrder); ok {
		r0 = rf(inboundOrder)
	} else {
		r0 = ret.Get(0).(model.InboundOrder)
	}

	if rf, ok := ret.Get(1).(func(model.InboundOrder) error); ok {
		r1 = rf(inboundOrder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockIInboundOrderService creates a new instance of MockIInboundOrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIInboundOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIInboundOrderService {
	mock := &MockIInboundOrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
