// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	model "github.com/maxwelbm/alkemy-g7.git/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockILocalityService is an autogenerated mock type for the ILocalityService type
type MockILocalityService struct {
	mock.Mock
}

// CreateLocality provides a mock function with given fields: locality
func (_m *MockILocalityService) CreateLocality(locality *model.Locality) (model.Locality, error) {
	ret := _m.Called(locality)

	if len(ret) == 0 {
		panic("no return value specified for CreateLocality")
	}

	var r0 model.Locality
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Locality) (model.Locality, error)); ok {
		return rf(locality)
	}
	if rf, ok := ret.Get(0).(func(*model.Locality) model.Locality); ok {
		r0 = rf(locality)
	} else {
		r0 = ret.Get(0).(model.Locality)
	}

	if rf, ok := ret.Get(1).(func(*model.Locality) error); ok {
		r1 = rf(locality)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *MockILocalityService) GetByID(id int) (model.Locality, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Locality
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (model.Locality, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) model.Locality); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Locality)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCarriers provides a mock function with given fields: id
func (_m *MockILocalityService) GetCarriers(id int) ([]model.LocalitiesJSONCarriers, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCarriers")
	}

	var r0 []model.LocalitiesJSONCarriers
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]model.LocalitiesJSONCarriers, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) []model.LocalitiesJSONCarriers); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.LocalitiesJSONCarriers)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSellers provides a mock function with given fields: id
func (_m *MockILocalityService) GetSellers(id int) ([]model.LocalitiesJSONSellers, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetSellers")
	}

	var r0 []model.LocalitiesJSONSellers
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]model.LocalitiesJSONSellers, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) []model.LocalitiesJSONSellers); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.LocalitiesJSONSellers)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockILocalityService creates a new instance of MockILocalityService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockILocalityService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockILocalityService {
	mock := &MockILocalityService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
