// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	model "github.com/maxwelbm/alkemy-g7.git/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockIProductsRepo is an autogenerated mock type for the IProductsRepo type
type MockIProductsRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: product
func (_m *MockIProductsRepo) Create(product model.Product) (model.Product, error) {
	ret := _m.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Product) (model.Product, error)); ok {
		return rf(product)
	}
	if rf, ok := ret.Get(0).(func(model.Product) model.Product); ok {
		r0 = rf(product)
	} else {
		r0 = ret.Get(0).(model.Product)
	}

	if rf, ok := ret.Get(1).(func(model.Product) error); ok {
		r1 = rf(product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *MockIProductsRepo) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *MockIProductsRepo) GetAll() (map[int]model.Product, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[int]model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[int]model.Product, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[int]model.Product); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]model.Product)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *MockIProductsRepo) GetByID(id int) (model.Product, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (model.Product, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) model.Product); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Product)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, product
func (_m *MockIProductsRepo) Update(id int, product model.Product) (model.Product, error) {
	ret := _m.Called(id, product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(int, model.Product) (model.Product, error)); ok {
		return rf(id, product)
	}
	if rf, ok := ret.Get(0).(func(int, model.Product) model.Product); ok {
		r0 = rf(id, product)
	} else {
		r0 = ret.Get(0).(model.Product)
	}

	if rf, ok := ret.Get(1).(func(int, model.Product) error); ok {
		r1 = rf(id, product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockIProductsRepo creates a new instance of MockIProductsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIProductsRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIProductsRepo {
	mock := &MockIProductsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
