with-expecter: false
filename: "{{.InterfaceName}}_mock.go"
dir: "internal/mocks"
outpkg: "mocks"
packages:
  github.com/maxwelbm/alkemy-g7.git/internal/service/interfaces:
    interfaces:
      IBuyerservice:
      ICarrierService:
      IEmployeeService:
      IInboundOrderService:
      ILocalityService:
      IProductBatchesService:
      IProductRecService:
      IProductService:
      IPurchaseOrdersService:
      ISectionService:
      ISellerService:
      IWarehouseService:
  github.com/maxwelbm/alkemy-g7.git/internal/repository/interfaces:
    interfaces:
      IBuyerRepo:
      ICarriersRepo:
      IEmployeeRepo:
      IInboundOrderRepository:
      ILocalityRepo:
      IProductBatchesRepo:
      IProductRecRepository:
      IProductsRepo:
      IPurchaseOrdersRepo:
      ISectionRepo:
      ISellerRepo:
      IWarehouseRepo:
