version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meli_fresh
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meli-fresh
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: user
      DB_NAME: meli_fresh
      DB_NET: tcp