name: CI

on:
  pull_request:
    branches:
      - '**' 
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run golangci-lint
        run: golangci-lint run --new-from-rev origin/main

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v3

      - name: Configurar Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.3'

      - name: Executar Testes
        run: go test ./... 
