name: CI

on:
  pull_request:
    branches:
      - '**' 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checar c贸digo do reposit贸rio
        uses: actions/checkout@v2

      - name: Configurar Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.3' 
          
      - name: Instalar GolangCI-Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2
          
      - name: Executar Linter
        run: go vet ./... && golangci-lint run

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checar c贸digo do reposit贸rio
        uses: actions/checkout@v2

      - name: Configurar Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.3'

      - name: Executar Testes
        run: go test ./... 
